// apps/web/src/app/app.tsx
import CssBaseline from '@mui/material/CssBaseline';
import { Header, ThemeProvider, Router } from './components';
import { GlobalNotificationProvider } from '../notification';
import { Box } from '@mui/system';

const App = () => {
  return (
    <Box height="100%" width="100%" display="flex" flexDirection="column">
      <ThemeProvider>
        <CssBaseline />
        <GlobalNotificationProvider>
          <Header />
          <Router />
        </GlobalNotificationProvider>
      </ThemeProvider>
    </Box>
  );
};

export { App };

// frontend/src/App.vue
<template>
  <div id="app">
    <Header/>
    <div class="main-container">
      <router-view/>
    </div>
  </div>
</template>

<script>
import Header from './components/Header'

export default {
  components: {
    Header
  }
}
</script>

<style>
  #app {
    width: 100%;
    height: 100%;
    display: flex;
    flex-direction: column;
  }

  body {
    position: fixed;
    top: 0;
    bottom: 0;
    margin: 0;
    width: 100%;
    height: 100%;
  }

  p {
    margin: 0;
  }

  .main-container {
    width: 100%;
    height: 100%;
    background-color: #e8e8e8
  }
</style>
